refactor: transfer flow
rsksmart/rif-rollup-wallet pull request #114
Opened 2023-09-07 13:37 UTC by annipi

2023-09-12 16:41 UTC, LordCheta requested changes
<img width="508" alt="Screenshot 2023-09-12 at 5 39 59 PM" src="https://github.com/rsksmart/rif-rollup-wallet/assets/27959051/3f6b8efa-7e6e-4e22-af06-36e50893a229">

Notice the transaction fees text is duplicated on this component

2023-09-12 16:47 UTC, annipi commented
> <img alt="Screenshot 2023-09-12 at 5 39 59 PM" width="508" src="https://user-images.githubusercontent.com/27959051/267401393-3f6b8efa-7e6e-4e22-af06-36e50893a229.png">
> Notice the transaction fees text is duplicated on this component

Good catch, to replicate it, is this the first time you are going to do a tx with this account?

2023-09-13 11:32 UTC, LordCheta approved these changes

2023-09-13 11:35 UTC, LordCheta approved these changes
LGTM!

2023-09-13 11:35 UTC, merged