refactor: history tab
rsksmart/rif-rollup-wallet pull request #61
Opened 2023-08-08 15:17 UTC by annipi

2023-08-08 19:56 UTC, sergio-jara requested changes
make sure the yarn.lock does not get corrupted

2023-08-08 19:56 UTC, sergio-jara commented on yarn.lock
> +    "@rsksmart/rif-rollup-nuxt-core": /Users/annipi/IovLabs/Rollup/rif-rollup-nuxt-core
remove

2023-08-09 08:13 UTC, LordCheta approved these changes

2023-08-09 18:25 UTC, sergio-jara approved these changes

2023-08-09 18:25 UTC, merged